In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# import the necessary packages
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D 
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dropout
from keras.layers.core import Dense
from keras import backend as K

Instructions for updating:
non-resource variables are not supported in the long term


Using TensorFlow backend.


In [15]:
import tensorflow as tf

print(tf.VERSION)

AttributeError: module 'tensorflow' has no attribute 'VERSION'

In [2]:
import tensorflow
from PIL import Image

Image.MAX_IMAGE_PIXELS = None

In [3]:
from tensorflow.keras.models import Sequential

In [4]:
# Example of creating a CNN model with many VGG blocks
from keras.models import Model
from keras.layers import Input
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.utils import plot_model
from keras.utils import to_categorical
# function for creating a vgg block
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import VGG16
# load an image from file
import sys
from numpy import load
import pandas as pd
import cv2
import matplotlib.pyplot as plt
from matplotlib.image import imread
from numpy import expand_dims

import pickle
from keras.preprocessing.image import array_to_img

from keras.preprocessing.image import ImageDataGenerator

from numpy import expand_dims
import numpy as np
import os


In [ ]:
/Users/denisdunn/Desktop/full_aerin/fifty_plus_class

In [ ]:
import os
directory=os.listdir("/Users/denisdunn/Desktop/full_aerin")

In [ ]:
file=('/Users/denisdunn/Desktop/full_aerin/fifty_plus_class/{}').format(directory[0])

In [ ]:
directory


In [ ]:
direct=('/Users/denisdunn/Desktop/full_aerin/{}').format(directory[1])

In [ ]:
import shutil
#newPath = shutil.move(file, direct)

In [ ]:
#os.makedirs(direct)

In [ ]:
#for files in directory:
   # direct=('/Users/denisdunn/Desktop/full_aerin/{}').format(files)
    #os.makedirs(direct)
    #file=('/Users/denisdunn/Desktop/full_aerin/fifty_plus_class/{}').format(files)
    #shutil.move(file, direct)
    
    

In [ ]:
test=('/Users/denisdunn/Desktop/full_aerin/F19_AERIN_NOAM_SET.tif/F19_AERIN_NOAM_SET.tif')

In [ ]:
os.listdir('/Users/denisdunn/Desktop/full_aerin')

In [ ]:
data=load_img(test)

In [ ]:
/Users/denisdunn/Desktop/full_aerin/AERIN_IM_MOODBOARD_LR.jpg/AERIN_IM_MOODBOARD_LR.jpg

In [ ]:
for picture in directory:
    try:
        pic=('/Users/denisdunn/Desktop/full_aerin/{}/{}').format(picture,picture)
        data=load_img(pic)
        samples = expand_dims(data, 0)
        saved=('/Users/denisdunn/Desktop/full_aerin/{}').format(picture)
        it = datagen.flow(samples,batch_size=1,save_to_dir=saved)
        for i in range(10):
            batch = it.next()
    except:
        pass

In [ ]:
picture

In [ ]:
data=('/Users/denisdunn/Desktop/full_aerin/{}/{}').format('picture','picture')

In [ ]:
data=load_img('/Users/denisdunn/Desktop/full_aerin/F19_AERIN_LIM_DIGITAL_1_HORIZ.jpg/F19_AERIN_LIM_DIGITAL_1_HORIZ.jpg')

In [ ]:
samples = expand_dims(data, 0)

In [ ]:
datagen = ImageDataGenerator(
    featurewise_center=True,
    featurewise_std_normalization=True,
    rotation_range=5,
    width_shift_range=10,
    height_shift_range=10,
    #brightness_range=(.95,1.2),
    channel_shift_range=20.0,
    horizontal_flip=True)

In [ ]:
it = datagen.flow(samples,batch_size=1,save_to_dir='/Users/denisdunn/Desktop/full_aerin/F19_AERIN_LIM_DIGITAL_1_HORIZ.jpg')
#it = datagen.flow(samples,batch_size=1)

In [ ]:

# generate samples and plot
for i in range(20):
  # define subplot
    #plt.subplot(330 + 1 + i)
  # generate batch of images
    batch = it.next()
# convert to unsigned integers for viewing 
    #image = batch[0].astype('uint32')
    
# plot raw pixel data 
    #plt.imshow(image)
# show the figure
#plt.show()

In [ ]:
array_to_img(image)

In [ ]:
import glob
print(glob.glob("/Users/denisdunn/Desktop/full_aerin/*.jpg"))

In [5]:
cat=os.listdir("/Users/denisdunn/Desktop/full_aerin")

In [174]:
test_pics=os.listdir('/Users/denisdunn/Desktop/aerin_test')

In [175]:
test_pics.remove('.DS_Store')

In [6]:
cat.remove('.DS_Store')

In [7]:
len(cat)

44

In [53]:
training_data=[]

In [54]:
len(training_data)

0

In [55]:
IMG_SIZE=10

In [56]:
DATADIR='/Users/denisdunn/Desktop/full_aerin'
CATEGORIES=cat

In [ ]:
#path =  os.path.join(DATADIR,category)
for category in CATEGORIES:
    path =  os.path.join(DATADIR,category)
    class_num = CATEGORIES.index(category)

In [ ]:
path

In [57]:
len(cat)

44

In [58]:
def create_training_data():
    for category in CATEGORIES:
        path =  os.path.join(DATADIR,category)
        class_num = CATEGORIES.index(category)
        for img in os.listdir(path):
            try:
                img_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
                
                new_array = cv2.resize(img_array,(IMG_SIZE,IMG_SIZE))
                test_image = new_array[...,::-1]
                training_data.append([test_image,class_num])
            except Exception as e:
                pass
create_training_data()
#cv2.IMREAD_GRAYSCALE

In [59]:
print(len(training_data))

1363


In [60]:
import random
random.shuffle(training_data)

In [61]:
X = []
y = []


In [62]:
for features, label in training_data:   
    X.append(features)
    y.append(label)
X=np.array(X).reshape(-1,IMG_SIZE,IMG_SIZE,1)

In [63]:
from keras.utils import to_categorical
y = to_categorical(y,num_classes=44,dtype='float32')

In [64]:
X=X/255.0

In [ ]:
p=cv2.imread('/Users/denisdunn/Desktop/shirt_test.png')

In [ ]:
image = load_img('/Users/denisdunn/Desktop/Screen Shot 2019-12-10 at 1.50.12 PM.png', target_size=(224, 224))

In [ ]:
image = img_to_array(image)

In [ ]:
image = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))

In [ ]:
image = preprocess_input(image)

In [65]:
from keras.callbacks import EarlyStopping

In [ ]:
# define a new model with random weights and 10 classes
new_input = Input(shape=(224, 224, 3))
model = VGG16( weights='imagenet',input_tensor=new_input, classes=1000)

In [ ]:
out=model.predict(image)
decode_predictions(out)

In [ ]:
#model.compile(loss='categorical_crossentropy',optimizer = 'adam',metrics=['accuracy'])
#model.fit(X,y,epochs=10,validation_split=.1)

In [47]:
len(y)

1363

In [330]:
import keras
from keras.layers import LeakyReLU
from keras.models import load_model
from keras.models import save_model

In [397]:
model = keras.Sequential([
    keras.layers.Conv2D(filters=128,kernel_size=(3,3),padding="same", activation="relu",input_shape=(10,10,1)),
    keras.layers.Flatten(),
    keras.layers.Dense(224, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    #keras.layers.Conv2D(filters=128,kernel_size=(3,3),padding="same", activation="relu"),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(.5),
    #keras.layers.Conv2D(filters=128,kernel_size=(3,3),padding="same", activation="relu"),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dropout(.2),
    keras.layers.Dense(28, activation='relu'),
    keras.layers.Dropout(.1),
    keras.layers.Dense(16, activation='relu'),
    
    keras.layers.Dense(44, activation='softmax'),
])

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
es=EarlyStopping(patience=5, monitor='loss',verbose=1)

model.fit(X, y, epochs=1000, batch_size=5,callbacks=[es])

test_loss, test_acc = model.evaluate(X, y)
print('Test accuracy:', test_acc)


Epoch 1/1000
1363/1363 [==============================] - 8s 6ms/step - loss: 3.7854 - accuracy: 0.0154
Epoch 2/1000
1363/1363 [==============================] - 8s 6ms/step - loss: 3.6881 - accuracy: 0.0345
Epoch 3/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 3.4860 - accuracy: 0.0470
Epoch 4/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 3.4243 - accuracy: 0.0433
Epoch 5/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 3.3519 - accuracy: 0.0594
Epoch 6/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 3.2545 - accuracy: 0.0712
Epoch 7/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 3.0974 - accuracy: 0.0682
Epoch 8/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 2.9482 - accuracy: 0.0726
Epoch 9/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 2.7544 - accuracy: 0.1101
Epoch 10/1000
1363/1363 [==============================] - 9s 7m

1363/1363 [==============================] - 9s 7ms/step - loss: 0.6544 - accuracy: 0.7755
Epoch 79/1000
1363/1363 [==============================] - 9s 7ms/step - loss: 0.5651 - accuracy: 0.7909
Epoch 00079: early stopping
1363/1363 [==============================] - 0s 183us/step
Test accuracy: 0.8173147439956665


In [335]:
#pic='/Users/denisdunn/Desktop/aerin_test/{}'.format(test_pics[6])
len(test_pics)
import time
from keras.models import Model

In [339]:
model.save_weights('11_of_28.h5')

In [414]:
#pic='/Users/denisdunn/Desktop/aerin_test/Screen Shot 2020-02-11 at 12.18.09 PM.png'
pic='/Users/denisdunn/Desktop/aerin_test/{}'.format(test_pics[8])
pic_test(pic)


KeyboardInterrupt: 

In [ ]:
load_img(pic)

In [ ]:
model.predict(answer)

In [69]:
def image_processing(test):
    #array_test=img_to_array(test)
    array_resize=cv2.resize(test,(IMG_SIZE,IMG_SIZE))
    return (np.array(array_resize).reshape(1,IMG_SIZE,IMG_SIZE,1))/255

In [131]:
denis=cv2.imread('/Users/denisdunn/Desktop/Screen Shot 2020-01-29 at 2.56.19 PM.png',cv2.IMREAD_GRAYSCALE)
#cv2.IMREAD_GRAYSCALE

array([29])

In [157]:
class_prob = model.predict(answer).flatten()
top_values_index = sorted(range(len(class_prob)), key=lambda i: class_prob[i])[:]

In [158]:
load_image(CATEGORIES[top_values_index

[15,
 4,
 9,
 31,
 20,
 32,
 41,
 24,
 16,
 1,
 18,
 13,
 28,
 25,
 8,
 7,
 22,
 30,
 38,
 26,
 33,
 27,
 40,
 37,
 6,
 19,
 34,
 17,
 21,
 2,
 39,
 35,
 11,
 3,
 43,
 0,
 14,
 12,
 5,
 23,
 42,
 10,
 36,
 29]

In [162]:
CATEGORIES[15]

'SP17_AERIN_DOR_HERO_1.jpg'

In [132]:
answer=image_processing(denis)

In [135]:
result=model.predict_classes(answer)
print(CATEGORIES[int(result)])

S20_AERIN_WG_DIGITAL_SQUARE_11.jpg


In [117]:
y_prob = model.predict(answer) 
max(y_prob)

array([3.6779360e-03, 2.8093849e-13, 3.9898109e-06, 8.5570301e-15,
       1.9124144e-08, 3.0494949e-09, 1.3197686e-05, 8.6762710e-17,
       3.8851532e-26, 2.2551899e-15, 9.7172573e-02, 1.3802902e-12,
       2.8197104e-04, 1.7033757e-05, 2.1874039e-06, 2.1235908e-27,
       7.7401595e-16, 1.1711552e-09, 6.8640402e-26, 6.1201408e-06,
       1.3556033e-04, 8.5409480e-01, 6.8692435e-10, 4.0883165e-02,
       1.1159374e-03, 8.2113518e-04, 4.3550582e-04, 1.0376082e-08,
       8.9226525e-14, 8.0570571e-06, 4.0355204e-16, 3.4637216e-19,
       5.8150299e-16, 5.6496909e-09, 2.0577718e-16, 4.2428530e-04,
       3.2172816e-06, 9.7216858e-14, 2.5099700e-15, 3.3749972e-11,
       2.5125715e-07, 9.0308295e-04, 1.4658516e-08, 4.6348359e-24],
      dtype=float32)

In [103]:
y_classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [99]:
model.predict_proba(answer)
y_prob.argmax(axis=-1)

array([[7.6119512e-05, 9.5760463e-15, 1.3716018e-05, 3.2071839e-14,
        1.9450461e-08, 9.4613881e-09, 1.6584640e-09, 8.2424371e-18,
        7.7262789e-22, 6.0804253e-13, 7.8762257e-01, 3.2652206e-08,
        5.2552402e-04, 8.3106925e-04, 3.0633262e-05, 3.0159240e-25,
        3.8762491e-13, 1.3903785e-10, 6.3360107e-19, 3.4574492e-05,
        5.0604181e-06, 2.3580598e-02, 1.4521406e-14, 1.7698675e-01,
        2.1003647e-04, 1.3935368e-04, 7.0902862e-04, 6.4197168e-11,
        5.9437916e-08, 5.2651425e-04, 2.2700809e-15, 2.8366718e-16,
        2.8832530e-18, 1.3610212e-07, 8.6150726e-16, 8.6445110e-03,
        2.6318496e-05, 1.8588560e-12, 8.2855442e-15, 6.1687651e-08,
        2.9364492e-07, 1.3107026e-05, 2.3904056e-05, 2.8601812e-19]],
      dtype=float32)

In [ ]:
pic='/Users/denisdunn/Desktop/HOL19_AERIN_ MODEL_F72.tif'

In [83]:
def pic_test(pic):
    denis=cv2.imread(pic,cv2.IMREAD_GRAYSCALE)
    answer=image_processing(denis)
    result=model.predict_classes(answer)
    direct='/Users/denisdunn/Desktop/full_aerin/{}/{}'.format(CATEGORIES[int(result)],CATEGORIES[int(result)])
    return load_img(direct)



In [ ]:
direct='/Users/denisdunn/Desktop/full_aerin/{}/{}'.format(CATEGORIES[int(result)],CATEGORIES[int(result)])

In [ ]:
pic_test('/Users/denisdunn/Desktop/_0_117.png')

In [ ]:
model.save('feb_5_size_25_batch5_model.h5')

In [ ]:
model.predict(answer)

In [ ]:
np.save('/Users/denisdunn/Desktop/DATADIR/X',X)
np.save('/Users/denisdunn/Desktop/DATADIR/y',y)

In [ ]:
model = keras.Sequential([
keras.layers.Conv2D(input_shape=(50,50,1),filters=64,kernel_size=(3,3),padding="same", activation="relu"),
keras.layers.Conv2D(filters=64,kernel_size=(3,3),padding="same", activation="relu"),
keras.layers.MaxPool2D(pool_size=(2,2),strides=(2,2)),
keras.layers.Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.Conv2D(filters=128, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.MaxPool2D(pool_size=(2,2),strides=(2,2)),
keras.layers.Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.Conv2D(filters=256, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.MaxPool2D(pool_size=(2,2),strides=(2,2)),
keras.layers.Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.MaxPool2D(pool_size=(2,2),strides=(2,2)),
keras.layers.Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.Conv2D(filters=512, kernel_size=(3,3), padding="same", activation="relu"),
keras.layers.MaxPool2D(pool_size=(2,2),strides=(2,2)),
keras.layers.Flatten(),
keras.layers.Dense(units=4096,activation="relu"),
keras.layers.Dense(units=4096,activation="relu"),
keras.layers.Dense(units=44, activation="softmax")])

In [ ]:
X.shape

In [ ]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
es=EarlyStopping(patience=20, monitor='acc',verbose=1)
model.fit(X, y, epochs=1000, batch_size=10,callbacks=[es])

test_loss, test_acc = model.evaluate(X, y)
print('Test accuracy:', test_acc)

In [1]:

# Load the TensorBoard notebook extension.
%load_ext tensorboard

In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from datetime import datetime
import io
import itertools
from packaging import version
from six.moves import range

import tensorflow as tf
from tensorflow import keras

import matplotlib.pyplot as plt
import numpy as np
import sklearn.metrics

print("TensorFlow version: ", tf.__version__)
assert version.parse(tf.__version__).release[0] >= 2, \
    "This notebook requires TensorFlow 2.0 or above."

TensorFlow version:  2.1.0


In [ ]:
# Clear out any prior log data.
!rm -rf logs

# Sets up a timestamped log directory.
logdir = "logs/train_data/" + datetime.now().strftime("%Y%m%d-%H%M%S")
# Creates a file writer for the log directory.
file_writer = tf.summary.create_file_writer(logdir)

# Using the file writer, log the reshaped image.
with file_writer.as_default():
  tf.summary.image("Training data", img, step=0)

In [ ]:
import cv2,time
import numpy as np
print(cv2.__version__)
import matplotlib.pyplot as plt
%matplotlib inline 

In [ ]:
/anaconda3/lib/python3.7/site-packages/cv2/data/haarcascade_frontalface_default.xml

In [ ]:
face_cascade=cv2.CascadeClassifier('/anaconda3/lib/python3.7/site-packages/cv2/data/haarcascade_frontalface_default.xml')

In [ ]:
face_cascade=cv2.CascadeClassifier('file:///Users/denisdunn/opt/anaconda3/lib/python3.7/site-packages/cv2/data/haarcascade_frontalface_default.xml')

In [ ]:
face_cascade

In [ ]:
gray=cv2.imread('/Users/denisdunn/Desktop/Ivb19_0881-319x319.png')

In [ ]:
faces=face_cascade.detectMultiScale(gray,scaleFactor=1.05,minNeighbors=5)

In [ ]:
print(faces)

In [ ]:
for x,y,w,h, in faces:
    img = cv2.rectangle(gray, (x,y), (x+w,y+h),(0,255,0),3)

In [ ]:
cv2.imshow('gray',img)

In [ ]:
#import cv2

#cvim2disp = cv2.imread('/Users/denisdunn/Desktop/Ivb19_0881-319x319.png')
cv2.imshow('img', img)
while(True):
    k = cv2.waitKey(33)
    if k == -1:  # if no key was pressed, -1 is returned
        continue
    else:
        break
cv2.destroyWindow('img')

In [ ]:
video=cv2.VideoCapture(0)
check,frame=video.read()
time.sleep(3) 
cv2.imshow('Capture',frame)
cv2.waitKey(0)
video.release()

In [ ]:
pwd

In [ ]:
cv2.destroyWindow('gray')

In [ ]:
filename = '/Users/denisdunn/Desktop/shirt_test.png'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

gray = np.float32(gray)
dst = cv2.cornerHarris(gray,2,3,0.04)

#result is dilated for marking the corners, not important
dst = cv2.dilate(dst,None)

# Threshold for an optimal value, it may vary depending on the image.
img[dst>0.01*dst.max()]=[0,0,255]

cv2.imshow('dst',img)
while(True):
    k = cv2.waitKey(33)
    if k == -1:  # if no key was pressed, -1 is returned
        continue
    else:
        break
cv2.destroyWindow('img')
#if cv2.waitKey(0) & 0xff == 27:
    #cv2.destroyAllWindows()


In [ ]:
filename = '/Users/denisdunn/Desktop/shirt_test.png'
img = cv2.imread(filename)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

gray = np.float32(gray)
dst = cv2.cornerHarris(gray,2,3,0.04)

#result is dilated for marking the corners, not important
dst = cv2.dilate(dst,None)

# Threshold for an optimal value, it may vary depending on the image.
img[dst>0.01*dst.max()]=[0,0,255]

cv2.imshow('dst',img)
cv2.waitKey()

cv2.destroyAllWindows()

In [ ]:
import tensorflow


In [ ]:
import keras

In [ ]:
cv2.destroyAllWindows()

In [ ]:
img = cv2.imread("image.jpg")
cv2.startWindowThread()
cv2.namedWindow("preview")
cv2.imshow("preview", im

In [ ]:

# Load the TensorBoard notebook extension
%load_ext tensorboard

In [ ]:
from keras.preprocessing.image import save_img

In [ ]:
img = load_img('/Users/denisdunn/Desktop/full_aerin/Aerin_Office_PhotoFrame_8x10.tif/Aerin_Office_PhotoFrame_8x10.tif')

In [ ]:
img_array = img_to_array(img)

In [ ]:
save_img('office_photoframe.jpg', img_array)

In [ ]:
pwd